### ISSUE TITLE
Fix on bazel build need to update major version

### ISSUE THREAD

**Issue by summer-ji-eng** [googleapis/gapic-generator-typescript#1110]
Fail PR #1094

**Comment by summer-ji-eng** [comment]
bazel update to 5.1.0 version

https://github.com/bazelbuild/rules_nodejs/releases

**Comment by summer-ji-eng** [comment]
Ping the @bazel/typescript `~4.6.1` for now. #1094 
But we still need to fix bazel rule and upgrade to major latest version.

**Comment by alexander-fenster** [comment]
Fixed in #1307.
