### ISSUE TITLE
bad generated param name `function_Param`

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator-typescript#1126]
https://github.com/googleapis/nodejs-functions/pull/146/files#diff-befd2ad0da13326aa9d2b9089e57ae16a5fa61ac16c2bd566035f10d46ff6e5dR1701

It's being generated as:

```
  cloudFunctionPath(project: string, location: string, functionParam: string) {
    return this.pathTemplates.cloudFunctionPathTemplate.render({
      project: project,
      location: location,
      function: function_Param, // this one is incorrect
    });
  }
```

**Comment by summer-ji-eng** [comment]
Weird. It should be a camel case. `id.get(param.toCamelCase())` [template code](https://github.com/googleapis/gapic-generator-typescript/blob/main/templates/typescript_gapic/src/%24version/%24service_client.ts.njk#L928)
And it works for  nodejs-speech [PR](https://github.com/googleapis/nodejs-speech/pull/854) and nodejs-service-center [PR](https://github.com/googleapis/nodejs-security-center/pull/468). These two both have the reserved words like `package` and `export`.

Will manual update for nodejs-function.

**Comment by summer-ji-eng** [comment]
@chingor13 Oh, I guess `synthtool` made some change to keep the `_`.

**Comment by summer-ji-eng** [comment]
Not generator issue.

Updated the PR in nodejs-functions. https://github.com/googleapis/nodejs-functions/pull/146/commits/c21c97e477bbcf32c8055cee4b6326b6e112a9bb
