### ISSUE TITLE
webpack, browser.js

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-typescript#125]
We don't generate `browser.ts` and `webpack.config.js`. They should be pretty much the same as currently in gapic-generator, but:

- in typescript
- using `ts-loader` plugin

**Comment by xiaozhenliu-gg5** [comment]
For `browser.js` in existing libraries, it only set `global.isBrowser = true;` and for typescript we check ` const isBrowser = typeof window !== 'undefined';` instead of checking the global value, I'm wondering do we still want this browser file?  Thanks

**Comment by alexander-fenster** [comment]
Hmm. Maybe we don't actually need it - let me think a little bit.

**Comment by alexander-fenster** [comment]
We don't need `src/browser.js` but we do need `webpack.config.js` having `src/index.ts` as an entry point as `ts-loader` plugin.

**Comment by xiaozhenliu-gg5** [comment]
Understood, added `webpack.config.js` template to micro-gen, thanks!
