### ISSUE TITLE
Generator creates .gitignore with `docs/`

### ISSUE THREAD

**Issue by chingor13** [googleapis/gapic-generator-typescript#1303]
If there is an important folder that has `docs/` in the path, it will be ignored.

See https://github.com/googleapis/repo-automation-bots/issues/4780

**Comment by chingor13** [comment]
This looks like the template: https://github.com/googleapis/gapic-generator-typescript/blob/main/templates/typescript_gapic/.gitignore.njk#L6

**Comment by sofisl** [comment]
Fixed in: https://github.com/googleapis/gapic-generator-typescript/pull/1318
