### ISSUE TITLE
Cannot use classes in protos

### ISSUE THREAD

**Issue by orgads** [googleapis/gapic-generator-typescript#1496]
#### Environment details

  - Programming language: Typescript
  - OS: Linux
  - Language runtime version: 20
  - Package version: 4.2.0

#### Steps to reproduce

When `esm` output is used, the import from protos.js is using `import type`, and this doesn't allow using the concrete classes in the namespaces, or other values that are not types.

This is example is based on `@google-cloud/speech` package, in which I only replaced the following line in `index.d.ts` to `import type *...`:
```ts
import * as protos from '../protos/protos';
```

Then in my code I have:
```ts
import { v1, v1p1beta1, protos as googleProtos } from '@google-cloud/speech';
// An import alias cannot reference a declaration that was imported using 'import type'.ts(1380)
import protos = googleProtos.google.cloud.speech;
function test() {
  // 'protos' cannot be used as a value because it was imported using 'import type'.ts(1361)
  const foo = new protos.v1.SpeechContext();
  // 'protos' cannot be used as a value because it was imported using 'import type'.ts(1361)
  return protos.v1.RecognitionConfig.AudioEncoding.LINEAR16;
}
```

Is there a reason not to use a simple `import` instead?

**Comment by alexander-fenster** [comment]
@sofisl can you take a look at this issue please?

**Comment by sofisl** [comment]
Hi @orgads, what do you mean by `when esm output is used?` We don't currently publish our packages in esm, although we do have plans to do so soon! In order to publish in esm, we need to do a lot of changes, and we're about to experiment with @google-cloud/tasks.

I'm not sure I understand what this means either: `Is there a reason not to use a simple import instead?` Where are you referring to?

**Comment by orgads** [comment]
I refer to the templates. See #1498 for my fix.

I only used `@google-cloud/speech` as a reference. I generated another package using esm output, and in index.d.ts the import of protos is `import type`. This is also wrong, since the js/cjs files *do* import the protos, while `import type` discards it in the js output.

**Comment by sofisl** [comment]
Gotcha! I think this is tied to another change that we made to the compileProtos step, which generates protos.js as [es6](https://github.com/googleapis/gax-nodejs/blob/8d962912600d59ede9b883e7e2f77220ff3e0628/tools/src/compileProtos.ts#L303-L315) (vs. amd).

In your experiment, try changing [this line](https://github.com/googleapis/google-cloud-node/blob/e7614ad5cb26d4828ac3cbc81d94bc7a9ea0a26c/packages/google-cloud-speech/package.json#L39) to:

```compileProtos esm/src --esm```

Could you let me know if that works for you?

**Comment by orgads** [comment]
Once again, there is no problem with the google speech package. Please refer to my PR #1498 and my previous comment.

**Comment by sofisl** [comment]
Hi @orgads, that line doesn't change anything in the speech package, it changes how the protos are compiled. It compiles the protos.js file into es6.

**Comment by orgads** [comment]
I know that. My problem is that the generated code is incorrect. Forget about the speech package.
