### ISSUE TITLE
comments with /*/ in path break code generation

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#177]
The secret manager API generates comments of the form:

 ```bash
 `projects/*/secrets/*/versions/latest` is an alias to the `latest`
```

The `*/` closes the multi-line comment, and breaks TypeScript.

**Comment by alexander-fenster** [comment]
We actually have this: 

https://github.com/googleapis/gapic-generator-typescript/blob/ef7482f77d0491a28beb4be28b6ac837afd010a4/templates/typescript_gapic/_util.njk#L83-L85

I wonder why it does not help here, maybe we don't apply this macro here? @xiaozhenliu-gg5 can you please take a look?
