### ISSUE TITLE
[usability] the Cloud Secret Manager API surface requires empty object for replication

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#179]
With the Secret Manager API, unless I provide an empty `automatic` object to `replication`, like so:

```js
    const secret = await client.createSecret({
      parent: 'projects/1111111',
      secret: {
        name: 'foo',
        replication: {
          automatic: {}
        }
      },
      secretId: 'foo'
    })
```

I receive:

```bash
INVALID_ARGUMENT: Secret.replication must be provided.
```

☝️ an empty object feels like a weird interpretation of the protos?

**Comment by xiaozhenliu-gg5** [comment]
From the proto file below, I see that for replication field, one of `automatic` or `user_managed ` is required, so here I guess either we pass an empty object for `automatic` or define an object as `user_managed`, API will be happy. https://github.com/googleapis/googleapis/blob/master/google/cloud/secretmanager/v1/resources.proto#L122

This is something related to API proto file, I will close this if no more further questions :) @bcoe
