### ISSUE TITLE
where should package.json pull its description from?

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#191]
As [@JustinBeckwith points out here](https://github.com/googleapis/nodejs-monitoring-dashboards/pull/1#discussion_r362983654) the description we pull in to the `package.json` initially is somewhat lackluster ... where should we get this from? perhaps we should place it from, perhaps this is another field we should put in `.repo-metadata.json`?

**Comment by xiaozhenliu-gg5** [comment]
We had a talk offline, and agree that we may not want to put extra logic for the description in `package.json`, but this file should be auto-generated and can be manually changed after that. I have updated the documentation of nodejs library generation. Please ping here if further work is needed. Thanks!
