### ISSUE TITLE
links to classes, types, etc., are not properly expanded in reference documentation

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#197]
I don't know if we should be fixing this during generation, or with an additional plugin we create for jsdoc.

As an example, see https://googleapis.dev/nodejs/scheduler/latest/v1beta1.CloudSchedulerClient.html#updateJob

> If a job is paused then the system will stop executing the job until it is re-enabled via [ResumeJob][google.cloud.scheduler.v1beta1.CloudScheduler.ResumeJob]. The state of the job is stored in [state][google.cloud.scheduler.v1beta1.Job.state]; if paused it will be set to [Job.State.PAUSED][google.cloud.scheduler.v1beta1.Job.State.PAUSED]. A job must be in [Job.State.ENABLED][google.cloud.scheduler.v1beta1.Job.State.ENABLED] to be paused.

**Comment by alexander-fenster** [comment]
Fixed by #316
