### ISSUE TITLE
eslint for JavaScript

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#198]
Whenever we create a new library, we make an effort to add at least one JavaScript sample in `samples/`:

1. to smoke test that the library actually works.
2. to give customers something to reference.

We should have JavaScript eslint rules as well as `gts`, to make sure these files follow coding style:

The deps:

```
npm i eslint eslint-config-prettier eslint-plugin-node eslint-plugin-prettier prettier --save-dev
```

The scripts:

```
 "fix": "gts fix && eslint samples --fix",
 "lint": "gts check && eslint samples",
```

**Comment by JustinBeckwith** [comment]
So ... I'd hold off on that.  I have something special for you :) In the version of `gts` on master, it's using `eslint` under the hood, and has a different set of configured rules for JavaScript and TypeScript.  By default, running `eslint --fix` will use our existing `eslint` top level config, and work against both TypeScript *and* JavaScript.

**Comment by alexander-fenster** [comment]
@JustinBeckwith That's exciting! Let's wait for `gts` v2 to land and see if any changes to the default generated `package.json` are needed.

**Comment by alexander-fenster** [comment]
No need to do it anymore since `gts` v2 handles it.
