### ISSUE TITLE
supporting multiple API versions

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#203]
with the micro generator, what's the mechanism for supporting multiple API versions?

I believe we would need to remove `src/index.ts` from generation, and update it manually? If this is the case, it would be good to figure out an alternate approach.

**Comment by summer-ji-eng** [comment]
Implement in synthtool `feat: implement multiple version for nodejs lib #504`
https://github.com/googleapis/synthtool/pull/504
