### ISSUE TITLE
lose useful comments for container-analysis

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/gapic-generator-typescript#238]
we lose some parameter comments for `getIamPolicy`, `setIamPolicy`, `testIamPermission` which from `grafeas/v1` 

ref: https://github.com/googleapis/nodejs-containeranalysis/pull/135

**Comment by alexander-fenster** [comment]
With the addition of `protos` to `.jsdoc.js`, those lost comments are not really useful, so I'll close this. I'll open two more issues instead :)
