### ISSUE TITLE
@returns comment lost

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-typescript#292]
All the text in `@returns` JSDoc blocks is lost (does not get to the resulting HTML).  This may or may not be a JSDoc bug. Anyway, we need to investigate and see if we can easily fix it.

**Comment by summer-ji-eng** [comment]
We use template of [jsdoc-fresh](https://www.npmjs.com/package/jsdoc-fresh) for JSDoc.
fix in jsdoc-fresh [PR](https://github.com/googleapis/jsdoc-fresh/pull/13)

**Comment by summer-ji-eng** [comment]
fixed with jsdoc-fresh [1.0.3](https://github.com/googleapis/jsdoc-fresh/releases/tag/v1.0.3) released.
