### ISSUE TITLE
nodejs: index.js shouldn't use lodash.merge

### ISSUE THREAD

**Issue by jmuk** [googleapis/gapic-generator-typescript#398]
The package.json generator doesn't say about this, but `lodash.merge` package is necessary for running pubsub API. It is conditional, it's only used when mixin exists; https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/nodejs/main.snip#L41

This is not a serious issue for now, since the generated package.json is not used in pubsub so far (hand-written one in google-cloud-node is used actually).

cc: @shinfan @landrito

**Comment by JustinBeckwith** [comment]
No lodash used here :)
