### ISSUE TITLE
Expose method to access LRO

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/gapic-generator-typescript#404]
(Node.js)

In [this Speech issue](https://github.com/googleapis/nodejs-speech/issues/10), a user brought up a good point-- we don't expose a method to reference an existing LRO. Can we add one, so that users can provide the operation's ID, then access the methods that GAX exposes?

**Comment by xiaozhenliu-gg5** [comment]
This will be taken care of by https://github.com/googleapis/gax-nodejs/pull/786. Close this since we have a  duplicate issue here: https://github.com/googleapis/gapic-generator-typescript/issues/170
