### ISSUE TITLE
[nodejs]: Generate src/doc_namespaces.js file

### ISSUE THREAD

**Issue by jmdobry** [googleapis/gapic-generator-typescript#405]
This file would contain a de-duped list of all the package names of all the proto files associated with an API. For example, in https://github.com/googleapis/nodejs-firestore we would end up with a `nodejs-firestore/src/doc_namespaces.js` file with the following:

```js
/**
 * @namespace google.protobuf
 */

/**
 * @namespace google.rpc
 */

/**
 * @namespace google.firestore.v1beta1
 */
```

if a `v1beta2` were to get released, then we'd have:

```js
/**
 * @namespace google.protobuf
 */

/**
 * @namespace google.rpc
 */

/**
 * @namespace google.firestore.v1beta1
 */

/**
 * @namespace google.firestore.v1beta2
 */
```

**Note:** It's important that we only define each namespace once in all the code.

**Comment by alexander-fenster** [comment]
Not for gapic-generator-typescript.
