### ISSUE TITLE
Allow an API endpoint to be explicitly passed

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator-typescript#408]
We currently hardcode `api-name.googleapis.com` in the Node.js API clients. We should take an `options.apiEndpoint` that allows the user to override this. This is useful for API producers wanting to use staging servers, customers wanting to test with emulators, etc.

See https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1630#issuecomment-322207900

**Comment by alexander-fenster** [comment]
We use an option from an annotation, and we let the user override it in the client constructor.
