### ISSUE TITLE
Improving output docs from generator

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator-typescript#409]
For the monitoring client the current doc examples are causing confusion as it generates `interval = {}` and gives no hint to the type or contents of interval. a `startTime` and `endTime` need to be provided. This PR updates the docstrings to be a bit more helpful. Is it possible to do this in the generator?

https://github.com/googleapis/nodejs-monitoring/pull/176

From other bug, instead providing, for instance (in node):
``` 
   * // Use an interval of the last 60 seconds
   * const interval ={
   *     startTime: { seconds: Date.now() / 1000 - 60,},
   *     endTime: { seconds: Date.now() / 1000,},
   * }
```

**Comment by alexander-fenster** [comment]
Not in scope of this project. @fhinkel Just FYI, I'm closing this old issue because it's not going to be implemented in the generator, I'm still unsure about the way we are going to move forward here.
