### ISSUE TITLE
bi-directional streaming calls with extra options

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-typescript#425]
Based on the discussion [here](https://github.com/googleapis/nodejs-firestore/pull/1019#discussion_r409169313):

```diff
- return this.innerApiCalls.listen(options);
+ return this.innerApiCalls.listen({}, options);
```

@schmidt-sebastian wrote:
> I do think the generated code is busted here. We use options to set an additional header, but the way this gets passed down here is as the request (if I remember this correctly). If we don't modify the code, the header is dropped. This only affects bidirectional streaming APIs with additional metadata, so probably just us. I do think we should fix this upstream at some point.

We need to figure out what's wrong there, and fix it in the generator.

**Comment by alexander-fenster** [comment]
Looks like #1066 fixes this one?

**Comment by summer-ji-eng** [comment]
> Looks like #1066 fixes this one?



> Looks like #1066 fixes this one?

Yes. Thanks for reference. Merge now. Will release new version with this change after Jan 2022 due to the code freeze policy.
