### ISSUE TITLE
enable release-please bot for tagging releases

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-typescript#448]
cc: bcoe@

We want to have a bot here that will just tag releases keeping track of patch, minor, and major versions. We are not going to release it to `npm` (while we could), we just need release tagging.

**Comment by bcoe** [comment]
@alexander-fenster make a `release-please.yml` that looks like this, in the `.github` folder:

https://github.com/yargs/yargs/blob/master/.github/release-please.yml

and don't add a `publish.yml`, should then work for you 👍

**Comment by alexander-fenster** [comment]
I know! :) I'll leave it to @xiaozhenliu-gg5 or @summer-ji-eng as an exercise :)

**Comment by summer-ji-eng** [comment]
#472
