### ISSUE TITLE
Bundle renovate PRs for dev dependencies

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-typescript#665]
This repository gets a significant number of pull requests from renovate for patch updates to dev dependencies.  Due to the volume, I think we should bundle these into a weekly rollup.

**Comment by alexander-fenster** [comment]
Agreed, will work on this after you-know-what-huge-thing-happens-this-week-that-takes-a-lot-of-time-to-do.

**Comment by JustinBeckwith** [comment]
I'm just going to leave this here:
https://github.com/googleapis/elixir-google-api/blob/master/.github/workflows/autoapprove.yml
