### ISSUE TITLE
Node: Expose ability to close GRPC channels

### ISSUE THREAD

**Issue by schmidt-sebastian** [googleapis/gapic-generator-typescript#68]
The Firestore Server SDK can initiate multiple clients if more than 100 requests are active. Especially for users that frequently create and destroy clients, this creates memory leaks as we are unable to close GRPC channels on destruction.

Would it be possible to expose a "close" API to the Node Veneer SDKs?

This would unblock https://github.com/googleapis/nodejs-firestore/pull/779 and https://github.com/googleapis/nodejs-firestore/issues/769

@alexander-fenster @thebrianchen

**Comment by busunkim96** [comment]
The generator lives in https://github.com/googleapis/gapic-generator/. @bcoe and @alexander-fenster could you help route this?

**Comment by busunkim96** [comment]
Ah I see it's already been moved, never mind! :woman_facepalming:

**Comment by merlinnot** [comment]
@alexander-fenster @schmidt-sebastian Hey guys, maybe we could align in this thread on the design for the API, so I could make a PR? It's very impactful for my company because of the Firestore memory leak and I'd be glad to help fixing it.

**Comment by schmidt-sebastian** [comment]
I will work on this next week. Please do bug me regularly for updates.
