### ISSUE TITLE
Secret Manager has no `projectPath` method

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-typescript#688]
I was doing some basic stuff with Secret Manager, and tried to do a `listSecrets`:
```js
const sm = new SecretManagerServiceClient();
const [secrets] = await sm.listSecrets({
  parent: 'projects/el-gato',
});
console.log(secrets);
```

I thought for places like this that expected a project URI (I think it wants a project URI...) I am used to having a `sm.projectPath` method I can use.  I was surprised when that didn't seem to exist on the service client.

**Comment by alexander-fenster** [comment]
As discussed - it's there, but not released yet. Need to draft a new release of secret manager.
