### ISSUE TITLE
Export common gax interfaces from client

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-typescript#769]
Looking at some TypeScript code that goes in depth, and finding that it's not uncommon to need several interfaces available only gax.  In the code I'm looking at today, it includes:

```ts
import {ClientOptions, CallOptions, PaginationCallback} from 'google-gax';
```

There are probably other interfaces folks may need.  Should we consider exporting gax broadly for consumers?

```ts
export * as gax from 'google-gax`;
```

This would have to happen from the `index.ts` in the root.

**Comment by alexander-fenster** [comment]
Yes we can do it. This will be a combined change in the generator and synthtool, let me do it some time after Thanksgiving.

**Comment by alexander-fenster** [comment]
It's been almost a year since that time and the client interface has not changed at all.  I don't think we want to make this change now at this point. Let's get back to this issue if the client interface starts changing a lot.
