### ISSUE TITLE
Possible typo in README.md

### ISSUE THREAD

**Issue by dh--** [googleapis/gapic-generator-typescript#800]
In https://github.com/googleapis/gapic-generator-typescript/blob/master/README.md#making-changes-to-the-generated-code

There's an instruction on how to run the generator:

`bazel run //:gapic-generator-typescript -- --help`

I don't know for sure, but I suspect that the line is either missing a flag, or shouldn't have the second --

Apologies, I didn't actually test if this is broken.

**Comment by hkdevandla** [comment]
@alexander-fenster , can you please triage this? Thanks!

**Comment by alexander-fenster** [comment]
Hi @dh--,

There is no mistake. The double dash, by convention, separate `bazel`'s own parameters from the parameters not consumed by `bazel` (those that get passed to the generator). Without `--`, the `--help` would've been passed to `bazel` so it would print _its own_ help page.

This is similar to how `grep` considers `--` as a stop of all options. If you need to `grep` for a string `-r` (not an `-r` option), you would do `grep -- -r`, here `--` signals `grep` that the remaining argv don't contain any dash-options.
