### ISSUE TITLE
No client is exported in the default version's(v1) index.ts

### ISSUE THREAD

**Issue by sofisl** [googleapis/gapic-generator-typescript#810]
When generating some libraries ([service control, service managemen](https://github.com/googleapis/googleapis/tree/master/google/api
)t, and IAM V1), it appears that there is no client exported in their versions, which halts library generation. 

This error pops up when running synthtool: `No client is exported in the default version's(v1) index.ts`

**Comment by alexander-fenster** [comment]
A few places where I'll need to fix it:

https://github.com/googleapis/gapic-generator-typescript/blob/master/src/schema/api.ts#L38-L48

https://github.com/googleapis/gapic-generator-typescript/blob/master/src/schema/proto.ts#L28-L33

https://github.com/googleapis/gapic-generator-typescript/blob/master/src/schema/proto.ts#L651-L655

**Comment by sofisl** [comment]
@alexander-fenster, friendly ping on this bug :) We'd love to generate these libraries by EOQ if possible!
