### ISSUE TITLE
Question: is there a way to permanently edit autogenerated docstrings

### ISSUE THREAD

**Issue by 0xSage** [googleapis/gapic-generator-typescript#824]
Issue: https://b.corp.google.com/issues/156973105

From the issue: "It looks like this docstring was copied from our [REST documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/sinks/update), but that is incorrect since the REST API accepts a string of comma separated, camelCase fields, and the nodejs API will accept a [FieldMask](https://googleapis.dev/nodejs/logging/latest/google.protobuf.html#.FieldMask) object as described here. I think these docs should remove the camelCase example, and also update the example Example: `updateMask=filter` to use correct FieldMask syntax." 

Question: 
1. How come we're not generating from gRPC reference instead of REST reference. The fields for UpdateSinkRequest look correct [here](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#google.logging.v2.UpdateSinkRequest).
2.  If not (1), how might we change part of the autogenerated documentation for `updateSink`.

**Comment by sofisl** [comment]
I apologize for this being so outdated, but I actually think this was already fixed 
- https://googleapis.dev/nodejs/logging/latest/google.logging.v2.IUpdateSinkRequest.html

These docs are usually generated from the protos, so generally they need to be updated there.
