### ISSUE TITLE
Generated code doesn't honor proto3 `optional` semantics

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator-typescript#848]
Google Ads API uses proto3 `optional` throughout, and the distinction between a field having a default value vs. not being present at all in a message is meaningful. The current behavior of the generated Node.js protos appears to be setting default values for all fields, regardless of whether the message actually has the field set.

**Comment by rosslavery** [comment]
Just adding +1 here to mention this is impacting the Node.js client library for the Google Ads API: https://github.com/Opteo/google-ads-api .

With the upcoming deprecation of Ads API V4/5 in June, developers using this library need enough time to migrate versions without encountering errors as a result of this bug.

**Comment by Zikoel** [comment]
Are we waiting for that issue the PR #852  ? That is chained to another PR on `google-gax` package [here](https://github.com/googleapis/gax-nodejs/pull/978) and that is chained to `protobufjs` PR [here](https://github.com/protobufjs/protobuf.js/pull/1584) ?

**Comment by alexander-fenster** [comment]
We are only waiting for protobuf.js release, then it will just go up through the dependency chain with no changes needed in google-gax or here.  To try it, `npm install protobuf.js@next` everywhere in the chain :)

**Comment by alexander-fenster** [comment]
(and as for protobuf.js release, it's coming soon - I'm working on it; it's a third party library but we can release it)

**Comment by alexander-fenster** [comment]
It should all work now (after reinstalling dependencies and regenerating protos with `npm run compile-protos`).

**Comment by alexander-fenster** [comment]
`protobufjs` v6.11.0

**Comment by Zikoel** [comment]
Absolutely awesome work, many thanks! I have a question: The issue is intended to be fixed on the version  `1.3.0` or on the next versions? I ask that because as I can see the dependency chain for the v1.3.0 is `gapic-generator-typescript@1.3.0 ->google-gax@2.11.2 -> protobufjs@6.10.2` but the fix is from `google-gax@2.12.0 -> protobufjs@6.11.0`, I'm wrong reading this ?
