### ISSUE TITLE
Trying to call textDetection() using base64 or buffer. Not working

### ISSUE THREAD

**Issue by cbdeveloper** [googleapis/gapic-generator-typescript#849]
I'm having trouble with an issue similar to issue https://github.com/googleapis/nodejs-vision/issues/9

I have a `base64` image string that I need to pass to `vision.textDetection()`, and nothing seems to work.

The issue that I've mentioned suggests the following:

---

![image](https://user-images.githubusercontent.com/43407798/88040708-36261680-cb41-11ea-8ab0-3ec00c1813ac.png)

---

Don't know if this should still be working for the most recent version, because this is what I'm doing:

```
const [textDetections] = await vision.textDetection(
     { image: {
         source: {
           content: imgBase64
      }
    }});
```

And this is what I'm getting:

```
{ Error: 3 INVALID_ARGUMENT: Request must specify image and features.
```

This is my `base64` string (it seems fine):

![image](https://user-images.githubusercontent.com/43407798/88040876-77b6c180-cb41-11ea-89ed-9c5a1f1be1e0.png)

Also tried the following:

```
const buffer = new Buffer(imgBase64, 'base64');
const arraybuffer  = Uint8Array.from(buffer).buffer;

const [textDetections] = await vision.textDetection({image: {
  // content: buffer           // <--- TRIED BOTH WITH BUFFER AND ARRAY BUFFER
  content: arraybuffer
}});
```

Nothing seems to work.

Also, the docs don't mention anything about it accepting a `base64` string.

https://googleapis.dev/nodejs/vision/latest/v1.ImageAnnotatorClient.html#textDetection

---

![image](https://user-images.githubusercontent.com/43407798/88041554-7d60d700-cb42-11ea-904a-d47870a164f4.png)

---

#### Environment details

  - OS: Firebase Cloud Function Node v10
  - Node.js version: 10
  - npm version: NA
  - `@google-cloud/vision` version: "@google-cloud/vision": "^2.1.1",

**Comment by hkdevandla** [comment]
@alexander-fenster , any updates on this? Thanks!
