### ISSUE TITLE
Generator should respect deprecated annotations

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/gapic-generator-typescript#853]
For gapic service rpcs:

option deprecated = true

Example: [proto](https://github.com/googleapis/googleapis/blob/d76f26f335b2b570b7e19d938f35f9894236e565/google/container/v1/cluster_service.proto#L175)

Expected:

The method should be annotated a `@deprecated` doc tag with the deprecation message, and emit a DeprecationWarning with the same message.

Summary doc: go/actools-client-library-deprecations

**Comment by alicejli** [comment]
Completed.
