### ISSUE TITLE
Bazel build support

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/gapic-generator-typescript#87]
We need to support bazel build for TypeScript micro-generator.

@vam-google will investigate if any problems exist for running Node.js code. 
@xiaozhenliu-gg5 or @alexander-fenster will implement the rules for calling micro-generator.

Calling just the generator should be pretty straightforward. Implementing test runs (`npm test` of the generated code) is a little bit trickier.

**Comment by jpoehnelt** [comment]
Any movement on this?

**Comment by alexander-fenster** [comment]
@jpoehnelt Expect in mid-March, after all libraries are converted from JavaScript to TypeScript.

**Comment by alexander-fenster** [comment]
Implemented!
