### ISSUE TITLE
Generate updated Docker image

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-typescript#950]
The latest Docker image we've published is from 2020-09-02, almost a year ago. It would be useful to generate a new image, particularly including the DIREGAPIC changes to the generator. This is blocking smoke tests in Showcase, https://github.com/googleapis/gapic-showcase/issues/827.

**Comment by summer-ji-eng** [comment]
Update the latest generator in docker
gcr.io/gapic-images/gapic-generator-typescript

**Comment by alexander-fenster** [comment]
Still does not work, see #1012
