### ISSUE TITLE
Accessing types from gax

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-typescript#975]
I am upgrading some of our bots to use the latest version of TypeScript.  With better typing for errors, I now need to get access to `GoogleError` in a few places, which is exported from `google-gax`.  I could import gax directly, but I was wondering if we should be exporting a few of the common gax types directly from each generated client, or how we'd want developers to access them.

**Comment by summer-ji-eng** [comment]
Make sense to export `GoogleError`. We could definitely support that.

**Comment by summer-ji-eng** [comment]
Now you are able to access the `GoogleError`, feel free to open if you have any question. Thank you.
```
const {GoogleError} = require('google-gax')
```
