### ISSUE TITLE
bug: wrong client name in the system test fixture for bigquery-storage

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/gapic-generator-typescript#985]
The PR in question:

https://github.com/googleapis/nodejs-bigquery-storage/pull/209

The files from owl-bot are:

https://github.com/googleapis/nodejs-bigquery-storage/blob/48e92f43ea60ee20ca6e460ec59d74b458665406/system-test/fixtures/sample/src/index.ts

and

https://github.com/googleapis/nodejs-bigquery-storage/blob/48e92f43ea60ee20ca6e460ec59d74b458665406/system-test/fixtures/sample/src/index.js

You can see both files are using `BigQueryWriteClient`, but this is not the correct name, so the system tests failed.

I manually changed them to `BigQueryStorageClient` and now the system tests is passing.

**Comment by summer-ji-eng** [comment]
Interesting. Thanks for the manual change to unblock API. 
I will take a look in October.

**Comment by summer-ji-eng** [comment]
In v1 `storage.proto`, 2 services: 
- [`BigQueryRead`](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/storage/v1/storage.proto#L46)
- [`BigQueryWrite`](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/storage/v1/storage.proto#L119)
However in service [`BigQueryStorage`](https://github.com/googleapis/googleapis/blob/master/google/cloud/bigquery/storage/v1beta1/storage.proto#L36) in `v1beta1` version.

And looks like the system-test use `BigQueryWriteClient` back ([code](https://github.com/googleapis/nodejs-bigquery-storage/blob/main/system-test/fixtures/sample/src/index.js#L24)). 

Close for now. If you have question, feel free to open it up. Thank you very much.
